from PyQt5 import QtCore, QtGui, QtWidgets
from presenter.presenter import Presenter

class Ui_Credit(object):

    def __init__(self):
        self.presenter = Presenter()

    def setupUi(self, Credit):
        Credit.setObjectName("Credit")
        Credit.resize(600, 600)
        Credit.setMinimumSize(QtCore.QSize(600, 600))
        Credit.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        Credit.setFont(font)
        Credit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.214, y1:0.965909, x2:0.2241, y2:0.0397727, stop:0.60199 rgba(30, 75, 128, 255), stop:1 rgba(56, 116, 181, 255));")
        self.sum = QtWidgets.QLabel(Credit)
        self.sum.setGeometry(QtCore.QRect(20, 20, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.sum.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.sum.setFont(font)
        self.sum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum.setAutoFillBackground(False)
        self.sum.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.sum.setObjectName("sum")
        self.sum_1 = QtWidgets.QLineEdit(Credit)
        self.sum_1.setGeometry(QtCore.QRect(240, 20, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.sum_1.setFont(font)
        self.sum_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sum_1.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.sum_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sum_1.setObjectName("sum_1")
        self.sum_2 = QtWidgets.QLabel(Credit)
        self.sum_2.setGeometry(QtCore.QRect(510, 20, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.sum_2.setFont(font)
        self.sum_2.setStyleSheet("QLabel { \n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.sum_2.setObjectName("sum_2")
        self.time_1 = QtWidgets.QLineEdit(Credit)
        self.time_1.setGeometry(QtCore.QRect(240, 90, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.time_1.setFont(font)
        self.time_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.time_1.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_1.setObjectName("time_1")
        self.time = QtWidgets.QLabel(Credit)
        self.time.setGeometry(QtCore.QRect(20, 90, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.time.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.time.setFont(font)
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setAutoFillBackground(False)
        self.time.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time.setObjectName("time")
        self.proc_3 = QtWidgets.QLabel(Credit)
        self.proc_3.setGeometry(QtCore.QRect(510, 160, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc_3.setFont(font)
        self.proc_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_3.setStyleSheet("QLabel { \n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.proc_3.setObjectName("proc_3")
        self.proc_2 = QtWidgets.QLineEdit(Credit)
        self.proc_2.setGeometry(QtCore.QRect(240, 160, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.proc_2.setFont(font)
        self.proc_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_2.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.proc_2.setObjectName("proc_2")
        self.proc = QtWidgets.QLabel(Credit)
        self.proc.setGeometry(QtCore.QRect(20, 160, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.proc.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc.setFont(font)
        self.proc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proc.setAutoFillBackground(False)
        self.proc.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc.setObjectName("proc")
        self.time_2 = QtWidgets.QComboBox(Credit)
        self.time_2.setGeometry(QtCore.QRect(510, 90, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.time_2.setFont(font)
        self.time_2.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time_2.setObjectName("time_2")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.type = QtWidgets.QLabel(Credit)
        self.type.setGeometry(QtCore.QRect(20, 230, 301, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.type.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.type.setFont(font)
        self.type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type.setAutoFillBackground(False)
        self.type.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.type.setObjectName("type")
        self.type_a = QtWidgets.QRadioButton(Credit)
        self.type_a.setEnabled(True)
        self.type_a.setGeometry(QtCore.QRect(360, 230, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.type_a.setFont(font)
        self.type_a.setStyleSheet("QRadioButton {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.type_a.setChecked(True)
        self.type_a.setObjectName("type_a")
        self.type_d = QtWidgets.QRadioButton(Credit)
        self.type_d.setGeometry(QtCore.QRect(360, 270, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.type_d.setFont(font)
        self.type_d.setStyleSheet("QRadioButton {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.type_d.setObjectName("type_d")
        self.pushButton = QtWidgets.QPushButton(Credit, clicked = lambda: self.calculate())
        self.pushButton.setGeometry(QtCore.QRect(170, 320, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.542, y1:0.494318, x2:1, y2:0, stop:0 rgba(135, 205, 205, 255), stop:1 rgba(209, 227, 181, 255));\n"
"color: #38817a;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #bbded6;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.res = QtWidgets.QLineEdit(Credit)
        self.res.setGeometry(QtCore.QRect(4, 380, 201, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.res.setFont(font)
        self.res.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.res.setObjectName("res")
        self.min = QtWidgets.QLabel(Credit)
        self.min.setGeometry(QtCore.QRect(240, 380, 131, 64))
        self.min.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.min.setText("")
        self.min.setObjectName("min")
        self.max = QtWidgets.QLabel(Credit)
        self.max.setGeometry(QtCore.QRect(440, 380, 131, 64))
        self.max.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.max.setText("")
        self.max.setObjectName("max")
        self.tochki = QtWidgets.QLabel(Credit)
        self.tochki.setGeometry(QtCore.QRect(380, 380, 61, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.tochki.setFont(font)
        self.tochki.setStyleSheet("QLabel { \n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.tochki.setText("")
        self.tochki.setObjectName("tochki")
        self.res_2 = QtWidgets.QLineEdit(Credit)
        self.res_2.setGeometry(QtCore.QRect(4, 450, 201, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.res_2.setFont(font)
        self.res_2.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.res_2.setObjectName("res_2")
        self.res_3 = QtWidgets.QLineEdit(Credit)
        self.res_3.setGeometry(QtCore.QRect(4, 520, 201, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.res_3.setFont(font)
        self.res_3.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.res_3.setObjectName("res_3")
        self.proc_nachisl = QtWidgets.QLabel(Credit)
        self.proc_nachisl.setGeometry(QtCore.QRect(240, 450, 144, 64))
        self.proc_nachisl.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.proc_nachisl.setText("")
        self.proc_nachisl.setObjectName("proc_nachisl")
        self.proc_dolg = QtWidgets.QLabel(Credit)
        self.proc_dolg.setGeometry(QtCore.QRect(240, 520, 144, 64))
        self.proc_dolg.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.proc_dolg.setText("")
        self.proc_dolg.setObjectName("proc_dolg")

        self.retranslateUi(Credit)
        QtCore.QMetaObject.connectSlotsByName(Credit)

    def retranslateUi(self, Credit):
        _translate = QtCore.QCoreApplication.translate
        Credit.setWindowTitle(_translate("Credit", "Taleayos Credit Calc"))
        self.sum.setText(_translate("Credit", "  Сумма кредита"))
        self.sum_2.setText(_translate("Credit", " руб"))
        self.time.setText(_translate("Credit", "  Срок кредита"))
        self.proc_3.setText(_translate("Credit", "%"))
        self.proc.setText(_translate("Credit", " Процентная ставка"))
        self.time_2.setItemText(0, _translate("Credit", "лет"))
        self.time_2.setItemText(1, _translate("Credit", "месяцев"))
        self.type.setText(_translate("Credit", " Тип ежемесячныч платежей"))
        self.type_a.setText(_translate("Credit", "Аннуитетные"))
        self.type_d.setText(_translate("Credit", "Дифференцированные"))
        self.pushButton.setText(_translate("Credit", "Рассчитать"))
        self.res.setText(_translate("Credit", " Ежемесячный платеж"))
        self.res_2.setText(_translate("Credit", " Начисленные проценты"))
        self.res_3.setText(_translate("Credit", " Долг + Проценты"))

    def calculate(self):
        self.clear()
        if self.validation():
            try:
                self.presenter.credit_calculate(int(self.sum_1.text()), int(self.time_1.text()),
                                                self.time_2.currentIndex(), float(self.proc_2.text()), self.type_d.isChecked())
            except Exception as exp:
                self.min.setText("ERROR!")
                return
            self.min.setText(str(round(self.presenter.credit.month_pay_min, 2)))
            self.max.setText(str(round(self.presenter.credit.month_pay_max, 2)))
            self.proc_nachisl.setText(str(round(self.presenter.credit.over_pay, 2)))
            self.proc_dolg.setText(str(round(self.presenter.credit.sum_pay, 2)))
        else:
            self.min.setText("ERROR!")

    def validation(self):
        if not self.sum_1.text().isnumeric() or not self.time_1.text().isnumeric() or not self.proc_2.text().isnumeric():
            return False
        if int(self.sum_1.text()) < 1:
            return False
        if self.time_2.currentText() == "лет":
            if int(self.time_1.text()) > 50 or int(self.time_1.text()) < 1:
                return False
        if self.time_2.currentText() == "месяцев":
            if int(self.time_1.text()) > 600 or int(self.time_1.text()) < 1:
                return False
        if 0 > float(self.proc_2.text()):
            return False
        return True

    def clear(self):
        self.presenter.credit.sum_pay = 0
        self.presenter.credit.over_pay = 0
        self.presenter.credit.month_pay_max = 0
        self.presenter.credit.month_pay_min = 0
        self.min.setText("")
        self.max.setText("")
        self.proc_nachisl.setText("")
        self.proc_dolg.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Credit = QtWidgets.QDialog()
    ui = Ui_Credit()
    ui.setupUi(Credit)
    Credit.show()
    sys.exit(app.exec_())
