from PyQt5 import QtCore, QtGui, QtWidgets
from presenter.presenter import *

class Ui_Deposit(object):
    def __init__(self):
        self.presenter = Presenter()

    def setupUi(self, Deposit):
        Deposit.setObjectName("Deposit")
        Deposit.resize(600, 600)
        Deposit.setMinimumSize(QtCore.QSize(600, 600))
        Deposit.setMaximumSize(QtCore.QSize(600, 600))
        Deposit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.214, y1:0.965909, x2:0.2241, y2:0.0397727, stop:0.60199 rgba(30, 75, 128, 255), stop:1 rgba(56, 116, 181, 255));")
        self.sum_1 = QtWidgets.QLineEdit(Deposit)
        self.sum_1.setGeometry(QtCore.QRect(240, 10, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.sum_1.setFont(font)
        self.sum_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sum_1.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.sum_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sum_1.setObjectName("sum_1")
        self.period_p = QtWidgets.QLabel(Deposit)
        self.period_p.setGeometry(QtCore.QRect(20, 250, 231, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.period_p.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.period_p.setFont(font)
        self.period_p.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.period_p.setAutoFillBackground(False)
        self.period_p.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.period_p.setObjectName("period_p")
        self.sum = QtWidgets.QLabel(Deposit)
        self.sum.setGeometry(QtCore.QRect(20, 10, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.sum.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.sum.setFont(font)
        self.sum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sum.setAutoFillBackground(False)
        self.sum.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.sum.setObjectName("sum")
        self.time = QtWidgets.QLabel(Deposit)
        self.time.setGeometry(QtCore.QRect(20, 70, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.time.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.time.setFont(font)
        self.time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time.setAutoFillBackground(False)
        self.time.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time.setObjectName("time")
        self.comboBox = QtWidgets.QComboBox(Deposit)
        self.comboBox.setGeometry(QtCore.QRect(270, 250, 231, 32))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sum_nalog = QtWidgets.QLineEdit(Deposit)
        self.sum_nalog.setGeometry(QtCore.QRect(14, 450, 265, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.sum_nalog.setFont(font)
        self.sum_nalog.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.sum_nalog.setObjectName("sum_nalog")
        self.sum_itog = QtWidgets.QLabel(Deposit)
        self.sum_itog.setGeometry(QtCore.QRect(292, 520, 143, 64))
        self.sum_itog.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.sum_itog.setText("")
        self.sum_itog.setObjectName("sum_itog")
        self.proc_3 = QtWidgets.QLabel(Deposit)
        self.proc_3.setGeometry(QtCore.QRect(510, 130, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc_3.setFont(font)
        self.proc_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_3.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.proc_3.setObjectName("proc_3")
        self.proc = QtWidgets.QLabel(Deposit)
        self.proc.setGeometry(QtCore.QRect(20, 130, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.proc.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc.setFont(font)
        self.proc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proc.setAutoFillBackground(False)
        self.proc.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc.setObjectName("proc")
        self.pushButton = QtWidgets.QPushButton(Deposit, clicked = lambda: self.on_deposit_clicked())
        self.pushButton.setGeometry(QtCore.QRect(180, 320, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.542, y1:0.494318, x2:1, y2:0, stop:0 rgba(135, 205, 205, 255), stop:1 rgba(209, 227, 181, 255));\n"
"color: #38817a;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: #bbded6;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.capital = QtWidgets.QRadioButton(Deposit)
        self.capital.setGeometry(QtCore.QRect(270, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.capital.setFont(font)
        self.capital.setStyleSheet("QRadioButton {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.capital.setObjectName("capital")
        self.sum_2 = QtWidgets.QLabel(Deposit)
        self.sum_2.setGeometry(QtCore.QRect(510, 10, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.sum_2.setFont(font)
        self.sum_2.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.sum_2.setObjectName("sum_2")
        self.res_proc_1 = QtWidgets.QLabel(Deposit)
        self.res_proc_1.setGeometry(QtCore.QRect(292, 380, 143, 64))
        self.res_proc_1.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.res_proc_1.setText("")
        self.res_proc_1.setObjectName("res_proc_1")
        self.time_2 = QtWidgets.QComboBox(Deposit)
        self.time_2.setGeometry(QtCore.QRect(510, 70, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.time_2.setFont(font)
        self.time_2.setStyleSheet("QComboBox {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time_2.setObjectName("time_2")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.sum_in = QtWidgets.QLineEdit(Deposit)
        self.sum_in.setGeometry(QtCore.QRect(14, 520, 265, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.sum_in.setFont(font)
        self.sum_in.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.sum_in.setObjectName("sum_in")
        self.time_1 = QtWidgets.QLineEdit(Deposit)
        self.time_1.setGeometry(QtCore.QRect(240, 70, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.time_1.setFont(font)
        self.time_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.time_1.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.time_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_1.setObjectName("time_1")
        self.proc_nalog = QtWidgets.QLabel(Deposit)
        self.proc_nalog.setGeometry(QtCore.QRect(20, 190, 191, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.452736, 0.58, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(55, 180, 193))
        gradient.setColorAt(1.0, QtGui.QColor(27, 108, 145))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.proc_nalog.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc_nalog.setFont(font)
        self.proc_nalog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.proc_nalog.setAutoFillBackground(False)
        self.proc_nalog.setStyleSheet("QLabel {\n"
"border-radius: 8px;\n"
"border: 2px solid #346357;\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(55, 180, 193, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc_nalog.setObjectName("proc_nalog")
        self.proc_2 = QtWidgets.QLineEdit(Deposit)
        self.proc_2.setGeometry(QtCore.QRect(240, 130, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.proc_2.setFont(font)
        self.proc_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_2.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.proc_2.setObjectName("proc_2")
        self.res_proc = QtWidgets.QLineEdit(Deposit)
        self.res_proc.setGeometry(QtCore.QRect(14, 380, 265, 64))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(18)
        self.res_proc.setFont(font)
        self.res_proc.setStyleSheet("QLineEdit {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.res_proc.setObjectName("res_proc")
        self.sum_nalog_1 = QtWidgets.QLabel(Deposit)
        self.sum_nalog_1.setGeometry(QtCore.QRect(292, 450, 143, 64))
        self.sum_nalog_1.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );\n"
"}")
        self.sum_nalog_1.setText("")
        self.sum_nalog_1.setObjectName("sum_nalog_1")
        self.proc_5 = QtWidgets.QLabel(Deposit)
        self.proc_5.setGeometry(QtCore.QRect(510, 190, 73, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(20)
        self.proc_5.setFont(font)
        self.proc_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_5.setStyleSheet("QLabel {\n"
"background-color: rgba( 255, 255, 255, 0% );;\n"
"}")
        self.proc_5.setObjectName("proc_5")
        self.proc_nalog_2 = QtWidgets.QLineEdit(Deposit)
        self.proc_nalog_2.setGeometry(QtCore.QRect(240, 190, 256, 51))
        font = QtGui.QFont()
        font.setFamily("Kannada MN")
        font.setPointSize(25)
        self.proc_nalog_2.setFont(font)
        self.proc_nalog_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.proc_nalog_2.setStyleSheet("QLineEdit {\n"
"background-color: qlineargradient(spread:pad, x1:0.452736, y1:0.58, x2:1, y2:0, stop:0 rgba(4, 95, 99, 255), stop:1 rgba(27, 108, 145, 255));\n"
"color: white;\n"
"}")
        self.proc_nalog_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.proc_nalog_2.setObjectName("proc_nalog_2")

        self.retranslateUi(Deposit)
        QtCore.QMetaObject.connectSlotsByName(Deposit)

    def retranslateUi(self, Deposit):
        _translate = QtCore.QCoreApplication.translate
        Deposit.setWindowTitle(_translate("Deposit", "Taleayos Deposit Calc"))
        self.period_p.setText(_translate("Deposit", " Периодичность выплат"))
        self.sum.setText(_translate("Deposit", "  Сумма вклада"))
        self.time.setText(_translate("Deposit", "  Срок размещения"))
        self.comboBox.setItemText(0, _translate("Deposit", "ежедневно"))
        self.comboBox.setItemText(1, _translate("Deposit", "еженедельно"))
        self.comboBox.setItemText(2, _translate("Deposit", "раз в месяц"))
        self.comboBox.setItemText(3, _translate("Deposit", "раз в квартал"))
        self.comboBox.setItemText(4, _translate("Deposit", "раз в полгода"))
        self.comboBox.setItemText(5, _translate("Deposit", "раз в год"))
        self.comboBox.setItemText(6, _translate("Deposit", "в конце периода"))
        self.sum_nalog.setText(_translate("Deposit", " Сумма налога"))
        self.proc_3.setText(_translate("Deposit", "%"))
        self.proc.setText(_translate("Deposit", " Процентная ставка"))
        self.pushButton.setText(_translate("Deposit", "Рассчитать"))
        self.capital.setText(_translate("Deposit", " Капитализация процентов"))
        self.sum_2.setText(_translate("Deposit", " руб"))
        self.time_2.setItemText(0, _translate("Deposit", "лет"))
        self.time_2.setItemText(1, _translate("Deposit", "месяцев"))
        self.sum_in.setText(_translate("Deposit", " Сумма на вкладе в конце срока"))
        self.proc_nalog.setText(_translate("Deposit", " Налоговая ставка"))
        self.res_proc.setText(_translate("Deposit", " Начисленные проценты"))
        self.proc_5.setText(_translate("Deposit", "%"))


    def on_deposit_clicked(self):
        self.clear()
        if self.validation():
            try:
                self.presenter.deposit_calculate(float(self.sum_1.text()), int(self.time_1.text()), self.time_2.currentIndex(), int(self.proc_2.text()),
                                                float(self.proc_nalog_2.text()), self.comboBox.currentIndex(), self.capital.isChecked())
            except Exception as exp:
                self.res_proc_1.setText("ERROR!")
                return
            self.res_proc_1.setText(str(round(self.presenter.deposit.percent, 2)))
            self.sum_nalog_1.setText(str(round(self.presenter.deposit.tax, 2)))
            self.sum_itog.setText(str(round(self.presenter.deposit.total_sum, 2)))
        else:
            self.res_proc_1.setText("ERROR!")

    def clear(self):
        self.presenter.deposit.tax = 0
        self.presenter.deposit.percent = 0
        self.presenter.deposit.total_sum = 0
        self.res_proc_1.setText("")
        self.sum_nalog_1.setText("")
        self.sum_itog.setText("")

    def validation(self):
        if not self.sum_1.text().isnumeric() or 0 > float(self.sum_1.text()):
            return False
        if not self.time_1.text().isnumeric():
            return False
        if self.time_2.currentText() == "лет":
            if 50 < int(self.time_1.text()) or int(self.time_1.text()) < 1:
                return False
        if self.time_2.currentText() == "месяцев":
            if int(self.time_1.text()) > 620 or int(self.time_1.text()) < 1:
                return False
        if not self.proc_2.text().isnumeric() or float(self.proc_2.text()) < 0:
            return False
        if not self.proc_nalog_2.text().isnumeric() or float(self.proc_nalog_2.text()) < 0:
            return False
        return True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Deposit = QtWidgets.QDialog()
    ui = Ui_Deposit()
    ui.setupUi(Deposit)
    Deposit.show()
    sys.exit(app.exec_())
